disabled_rules: # rule identifiers to exclude from running
  - todo
  - vertical_parameter_alignment
  - legacy_constructor #NSMakeRange needed
  - cyclomatic_complexity #disable did not work
  - trailing_comma
opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Nuke

#trailing_comma:
#  mandatory_comma: true

variable_name:
  excluded: # excluded via string array
    - id
    - x
    - y

#legacy_constructor
#  excluded:
#    - NSMakeRange
