disabled_rules: # rule identifiers to exclude from running
  - todo
  - vertical_parameter_alignment
  - legacy_constant #NSMakeRange needed
  - cyclomatic_complexity #disable did not work
  - trailing_comma
opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Nuke

#trailing_comma:
#  mandatory_comma: true

#line_length: 150

type_body_length:
  warning: 300
  error: 1200

file_length:
  warning: 500
  error: 1200

variable_name:
  excluded: # excluded via string array
    - id
    - x
    - y

#legacy_constant
#  excluded:
#    - NSMakeRange
